name: crem
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - rdkit>=2017.09
  - numpy
  - joblib
  - tqdm
  - pandas
  - setuptools>=77
  - setuptools_scm>=8
  - wheel
  - python-build
  - pip
  - pytest
