#!/usr/bin/env bash
#PBS -l select=1:ncpus=32
#PBS -k oe

RADIUS=2

cd ~/imtm/crem/orgelm_pains_db
source ~/anaconda3/bin/activate rdkit-1709

python3 ~/python/crem/frag_to_env_mp.py -i ~/imtm/crem/frags.txt -o r${RADIUS}.txt -k ~/imtm/crem/organic_elements_pains_abc.ids -r ${RADIUS} -c 32 -v
sort r${RADIUS}.txt | uniq -c > r${RADIUS}_c.txt
#python3 ~/python/crem/import_env_to_db.py -i r${RADIUS}_c.txt -o replacements.db -t radius${RADIUS} -c -v
